// Generated by: go run ./cmd/contracts. Do not edit.
export type UserDTO = {
  id: string;
  username: string;
  name: string;
  bio: string | null;
  website: string | null;
  location: string | null;
  photoURL: string;
  coverPhotoURL: string | null;
  theme: string | null;
  accent: string | null;
  verified: boolean;
  isAdmin: boolean;
  isBanned: boolean;
  pinnedTweet: string | null;
  createdAt: string;
  updatedAt: string | null;
  following: Array<string>;
  followers: Array<string>;
  totalTweets: number;
  totalPhotos: number;
};
export type MediaDTO = {
  id: string;
  src: string;
  alt: string;
  type: string;
};
export type ParentDTO = {
  id: string;
  username: string;
};
export type TweetDTO = {
  id: string;
  text: string | null;
  images: Array<MediaDTO> | null;
  parent: ParentDTO | null;
  createdBy: string;
  createdAt: string;
  updatedAt: string | null;
  userLikes: Array<string>;
  userRetweets: Array<string>;
  userReplies: number;
};
export type LoginInput = {
  email: string;
  password: string;
};
export type PostInput = {
  text: string;
  parentId: string | null;
  mediaIds: Array<string>;
};
export type QueryInput = {
  collection: string;
  constraints: Array<Constraint>;
  limit: number;
  cursor?: string;
  count?: boolean;
};
export type Constraint = {
  kind: string;
  field?: string;
  op?: string;
  value?: unknown;
};
