package main

import (
	"fmt"
	"reflect"
	"socialmedia/backend/internal/app"
	"strings"
)

func ts(t reflect.Type) string {
	switch t.Kind() {
	case reflect.String:
		return "string"
	case reflect.Bool:
		return "boolean"
	case reflect.Int, reflect.Int64:
		return "number"
	case reflect.Pointer:
		return ts(t.Elem()) + " | null"
	case reflect.Slice:
		return "Array<" + ts(t.Elem()) + ">"
	case reflect.Interface:
		return "unknown"
	case reflect.Struct:
		return t.Name()
	}
	panic(t.String())
}
func main() {
	fmt.Println("// Generated by: go run ./cmd/contracts. Do not edit.")
	for _, v := range []any{app.UserDTO{}, app.MediaDTO{}, app.ParentDTO{}, app.PostDTO{}, app.LoginInput{}, app.PostInput{}, app.QueryInput{}, app.Constraint{}} {
		t := reflect.TypeOf(v)
		fmt.Printf("export type %s = {\n", t.Name())
		for i := 0; i < t.NumField(); i++ {
			f := t.Field(i)
			parts := strings.Split(f.Tag.Get("json"), ",")
			opt := ""
			if len(parts) > 1 && parts[1] == "omitempty" {
				opt = "?"
			}
			fmt.Printf("  %s%s: %s;\n", parts[0], opt, ts(f.Type))
		}
		fmt.Println("};")
	}
}
